### ISSUE TITLE
Spurious test failures

### ISSUE THREAD

**Issue by vmx** [vmx/temp-env#13]
On MacOS there was a test failure on CI: https://github.com/vmx/temp-env/actions/runs/3150858960/jobs/5124127616.

It looks like it hit some race condition. This sounds like a bug to me, this library shouldn't have race conditions and lead to random test failures that disappear when rerun: https://github.com/vmx/temp-env/actions/runs/3150858960/jobs/5124196938

If anyone has time to look into that, that would be great.

**Comment by robjtede** [comment]
Those logs have expired. If this happens again, probably copy the info into this issue.

**Comment by vmx** [comment]
Another failure, this time on Windows: https://github.com/vmx/temp-env/actions/runs/6051601020/job/16423400083?pr=22

```
failures:

---- tests::test_with_vars_set_returning stdout ----
thread 'tests::test_with_vars_set_returning' panicked at '`ONE` must not be set.', src\lib.rs:342:9
```

I've attached the full log, in case the link expired again.
[2023-09-01-windows-failing.log](https://github.com/vmx/temp-env/files/12499805/2023-09-01-windows-failing.log)

**Comment by xfix** [comment]
There is nothing to enforce `ONE` will have any particular value at beginning of `test_with_vars_set_returning` test. This test by this point doesn't access the mutex, so any test that affects `ONE` environment variable could affect it.
