### ISSUE TITLE
API not ideal when exclusively unsetting environment variables

### ISSUE THREAD

**Issue by fabian-braun** [vmx/temp-env#2]
I noticed that the API is a bit clumsy, when only unsetting variables.

The following does not compile:
```rust
#[test]
    fn test_function_works_when_env_var_missing() {
        temp_env::with_var("SHOULD_BE_MISSING", None, || {
            let actual = env::var("SHOULD_BE_MISSING");
            let expected = Result::Err(VarError::NotPresent);
            assert_eq!(expected, actual);
        })
    }
```

It only works like so:
```rust
#[test]
    fn test_function_works_when_env_var_missing() {
        //                vvvvvvvvvvvv
        temp_env::with_var::<_,&str,_>("SHOULD_BE_MISSING", None, || {
            let actual = env::var("SHOULD_BE_MISSING");
            let expected = Result::Err(VarError::NotPresent);
            assert_eq!(expected, actual);
        })
    }
```

The compiler error is not that nice either:
```
error[E0283]: type annotations needed
   --> src/test.rs:111:9
    |
111 |         temp_env::with_var("SHOULD_BE_MISSING", None, || {
    |         ^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `V` declared on the function `with_var`
    |
    = note: cannot satisfy `_: AsRef<OsStr>`
note: required by a bound in `with_var`
   --> /Users/fabian.braun/.cargo/registry/src/github.com-1ecc6299db9ec823/temp-env-0.1.0/src/lib.rs:57:8
    |
57  |     V: AsRef<OsStr> + Clone,
    |        ^^^^^^^^^^^^ required by this bound in `with_var`
help: consider specifying the type arguments in the function call
    |
111 |         temp_env::with_var::<K, V, F>("SHOULD_BE_MISSING", None, || {
    |                           +++++++++++
```

This is a side-effect of using `AsRef<OsStr>` as a type bound instead of a concrete type. I assume you made that change to comply with the API of `env::with_var`. Do you have an idea how to go about this?

**Comment by fabian-braun** [comment]
Some options:

- use the concrete type `&str` instead of `V: AsRef<OsStr> + Clone`. I'm not fully aware of the implications of that
- introduce a specific function for that need `env::with_var_unset`

**Comment by vmx** [comment]
Another way is to to add the type annotation to `None` like this: `None::<&str>`. Perhaps documenting that issue would be enough?

> * use the concrete type `&str` instead of `V: AsRef<OsStr> + Clone`. I'm not fully aware of the implications of that

You couldn't use the `String` type then. So e.g. `temp_env::with_var("MY_VAR", Some("value".to_string()), || { … });` wouldn't work.

> * introduce a specific function for that need `env::with_var_unset`
 
That's also a way.
